# Trajectory Synthetic Data Generator Configuration

# AWS Bedrock Settings
bedrock:
  region: "us-east-1"
  model_id: "global.anthropic.claude-sonnet-4-20250514-v1:0"
  embedding_model_id: "amazon.titan-embed-text-v2:0"
  max_tokens: 64000
  temperature: 0.7

# PDF Processing
pdf_processing:
  extract_images: true
  chunk_size: 4000
  chunk_overlap: 200
  use_vision_for_images: true

# ChromaDB Settings
chromadb:
  persist_directory: "data/chromadb"
  collection_name: "document_chunks"
  distance_metric: "cosine"

# Tool Definitions
tools:
  definitions_file: "config/tools.json"
  enable_tool_use: true

# Generation Settings
generation:
  target_qa_pairs: 1500  # For no-seed mode
  expansion_factor: 90    # Variations per seed
  
  # Complexity distribution (for no-seed mode)
  complexity_distribution:
    simple: 0.3    # 30%
    medium: 0.5    # 50%
    complex: 0.2   # 20%

# Variation Types
variations:
  personas: ["professional", "casual", "technical", "anxious", "directive"]
  query_modifications: ["add_context", "remove_details", "increase_complexity", "simplify"]
  tool_sequences: ["sequential", "batch", "conservative", "aggressive", "minimal"]

# Diversity & Curation
curation:
  similarity_threshold: 0.85
  enable_dual_phase: true
  min_quality_score: 7.0

# Output Settings
output:
  format: "jsonl"  # "jsonl" | "json" | "both"
  output_dir: "data/output"
  save_trajectories: true
  organize_by_complexity: true
  
  # Output schema format
  schema:
    # Format: "openai" | "custom" | "trajectory"
    type: "trajectory"
    
    # Custom field names (for type: "trajectory")
    fields:
      query: "Q"              # Query/Question
      cot: "COT"              # Chain of Thought
      tools: "Tool Set"      # Tool calls
      decision: "Decision"    # Final answer/decision
    
    # Include options
    include_reasoning: true    # Include COT
    include_metadata: true     # Include source metadata
    include_tool_results: false  # Include full tool results (can be large)

# Logging
logging:
  level: "INFO"
  file: "logs/trajectory_generator.log"